return {
    intro = function(cutscene)
        Game:setFlag("hometown_time", "night")
        cutscene:loadMap("light/hometown/torielhouse/kris_room")
        Game.world.music:stop()
        Game.world.music:play("jitterbug_muffled")
        cutscene:fadeIn(2, {music = false})
        local k = cutscene:getCharacter("kris")
        k:setPosition(502, 256)
        k:setSprite("sleepless_left")
        cutscene:wait(2)
        Assets.playSound("sans_muffle")
        cutscene:wait(0.5)
        Assets.playSound("wing")
        k:shake()
        k:setSprite("sleepless_right")
        cutscene:wait(2)
        Assets.playSound("toriel_muffled")
        cutscene:wait(0.5)
        Assets.playSound("wing")
        k:shake()
        k:setSprite("sleepless_left")
        cutscene:wait(1)
        Assets.playSound("sans_muffle")
        cutscene:wait(0.5)
        Assets.playSound("rimshot_muffled")
        cutscene:wait(0.7)
        Assets.playSound("wing")
        k:shake()
        k:setSprite("sleepless_right")

            --gotocutscene when we do the transition to the church
    end
}