local FuckYouEncounter, super = Class(Encounter)

function FuckYouEncounter:init()
    super.init(self)

    -- Text displayed at the bottom of the screen at the start of the encounter
    self.text = [==[
    [color:green][shake:10]FUCK YOU 392 ENEMIES[shake:0]
]==]

    self.music = "titan_spawn2"
    self.background = true

    self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
	self:addEnemy("nymph_spawn")
    self:addEnemy("balthizard")
    self:addEnemy("bibliox")
    self:addEnemy("guei")
    self:addEnemy("mizzle")
    self:addEnemy("organikk")
    self:addEnemy("wicabel")
    self:addEnemy("winglade")
    self.g = self:addEnemy("3d", 501, 269)
    self.rainbow_timer = 0
    self.bg_texture = Assets.getTexture("battle/backgrounds/fountainbglooped")
	self.xx = 0
	self.transition_x = SCREEN_WIDTH
	self.con = 0
	self.shape_timer = 0
    self.particles = {}
	self.particle_tex = Assets.getFramesOrTexture("bullets/cube/cube")
	self.particle_dtmult = 0
    self.holdbreath = false
	self.transition_end_alpha = 0
    self.background = false
    self.siner = 0
	self.rage_anim_speed = 1
	self.raged = false
    self:addEnemy("titan", 500, 350)
    self:addEnemy("tester")
    self:addEnemy("jellycruel")
    self:addEnemy("dogfood")
    self.toggle_shadow_mantle_all_bullets = true
    self.banish_goal = nil

    self.reduced_tension = true
    self.light_size = 48
    self.purified = false
    self.difficulty = 1
	self.is_prism = false
	self.prism_bg_con = 0
end

function FuckYouEncounter:createBackground()
    return Game.battle:addChild(PrismBattleBackground())
end

function FuckYouEncounter:onTurnEnd() 
    self.difficulty = self.difficulty + 1
end

function FuckYouEncounter:beforeStateChange(old, new, reason)
	if reason == "PURIFIED" then return end -- somehow prevents a stack overflow
    if (new == "DEFENDING" or old == "CUTSCENE") and self.purified then
        Game.battle:setState("VICTORY", "PURIFIED")
    end
end

function FuckYouEncounter:createSoul(x, y, color)
	local soul = Soul(x, y, color)
	if self.holdbreath then
		soul.speed = 5
	end
    return soul
end

function FuckYouEncounter:update()
    self.siner = self.siner + DTMULT
	if self.con <= 2 then
		self.g.y = self.g.y + math.cos(self.siner/10)*2
	end
end

function FuckYouEncounter:canSwoon(target)
    return Game.battle.encounter.raged
end

function FuckYouEncounter:isAutoHealingEnabled(target)
    return not Game.battle.encounter.raged
end

return FuckYouEncounter