return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.12.1",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 24,
  height = 30,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 12,
  nextobjectid = 231,
  properties = {
    ["border"] = "base_sanctum",
    ["music"] = "church_study_slower",
    ["name"] = "Old Man's Study"
  },
  tilesets = {
    {
      name = "bg_dw_church_tileset_new",
      firstgid = 1,
      filename = "../../../tilesets/bg_dw_church_tileset_new.tsx",
      exportfilename = "../../../tilesets/bg_dw_church_tileset_new.lua"
    },
    {
      name = "church_objects",
      firstgid = 583,
      filename = "../../../tilesets/church_objects.tsx",
      exportfilename = "../../../tilesets/church_objects.lua"
    },
    {
      name = "libraryexcerpt",
      firstgid = 686,
      filename = "../../../tilesets/libraryexcerpt.tsx",
      exportfilename = "../../../tilesets/libraryexcerpt.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../assets/sprites/backgrounds/gerson_study_base.png",
      id = 2,
      name = "bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 24,
      height = 30,
      id = 1,
      name = "tile",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 716, 716, 716, 716,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 716, 716, 716, 716,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 716, 716, 716, 716,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 716, 716, 716, 716,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 716, 716, 716, 716,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 716, 716, 716, 716,
        74, 74, 359, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 716, 716, 716, 716,
        354, 378, 74, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 716, 716, 716, 716,
        86, 86, 86, 86, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 716, 716, 716, 716,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_fireplace",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 414,
          y = 684,
          width = 140,
          height = 68,
          rotation = 0,
          opacity = 1,
          gid = 623,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 722,
          y = 284,
          width = 96,
          height = 88,
          rotation = 0,
          opacity = 1,
          gid = 631,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 54,
          width = 132,
          height = 54,
          rotation = 0,
          opacity = 1,
          gid = 651,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 828,
          y = 54,
          width = 132,
          height = 54,
          rotation = 0,
          opacity = 1,
          gid = 2147484299,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 200,
          width = 30,
          height = 70,
          rotation = 0,
          opacity = 1,
          gid = 642,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 34,
          y = 200,
          width = 30,
          height = 70,
          rotation = 0,
          opacity = 1,
          gid = 642,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 34,
          y = 472,
          width = 30,
          height = 70,
          rotation = 0,
          opacity = 1,
          gid = 642,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 472,
          width = 30,
          height = 70,
          rotation = 0,
          opacity = 1,
          gid = 642,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "gerson_table",
          type = "",
          shape = "rectangle",
          x = 334,
          y = 1055,
          width = 266,
          height = 96,
          rotation = 0,
          opacity = 1,
          gid = 619,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "rectangle",
          x = 740,
          y = 794,
          width = 132,
          height = 54,
          rotation = 0,
          opacity = 1,
          gid = 2147484307,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects_tableitems",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 127,
          name = "sprite",
          type = "",
          shape = "point",
          x = 480,
          y = 990,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["speed"] = 0.333333333,
            ["texture"] = "effects/shine_white"
          }
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 388,
          y = 1017,
          width = 40,
          height = 26,
          rotation = 0,
          opacity = 1,
          gid = 664,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 446,
          y = 1021,
          width = 26,
          height = 32,
          rotation = 0,
          opacity = 1,
          gid = 661,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 492,
          y = 1021,
          width = 26,
          height = 18,
          rotation = 0,
          opacity = 1,
          gid = 662,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 524,
          y = 1043,
          width = 56,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 663,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          type = "",
          shape = "rectangle",
          x = 430,
          y = 844,
          width = 108,
          height = 104,
          rotation = 0,
          opacity = 1,
          gid = 640,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          type = "",
          shape = "rectangle",
          x = 366,
          y = 872,
          width = 222,
          height = 102,
          rotation = 0,
          opacity = 1,
          gid = 660,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects_party",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 154,
          y = 910,
          width = 116,
          height = 152,
          rotation = 0,
          opacity = 1,
          gid = 618,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 604,
          y = 1072,
          width = 36,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 621,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 334,
          y = 1076,
          width = 44,
          height = 26,
          rotation = 0,
          opacity = 1,
          gid = 620,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 1014,
          width = 28,
          height = 28,
          rotation = 0,
          opacity = 1,
          gid = 622,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 642,
          y = 1046,
          width = 28,
          height = 28,
          rotation = 0,
          opacity = 1,
          gid = 622,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 580,
          y = 724,
          width = 68,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 617,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          type = "",
          shape = "rectangle",
          x = 100,
          y = 303,
          width = 68,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 617,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 242,
          y = 1045,
          width = 68,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 617,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = -40,
          y = 920,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "0_base_sanctum/base_east_3",
            ["marker"] = "entry_study"
          }
        },
        {
          id = 107,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 240,
          width = 110,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["map"] = "0_base_sanctum/base_center",
            ["marker"] = "entry_east"
          }
        },
        {
          id = 120,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 730,
          y = 240,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "study.fountain"
          }
        },
        {
          id = 123,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 988,
          width = 240,
          height = 67,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "study.table"
          }
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 989,
          width = 240,
          height = 12,
          rotation = 0,
          opacity = 1,
          gid = 672,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 333,
          y = 734,
          width = 76,
          height = 38,
          rotation = 0,
          opacity = 1,
          gid = 616,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 558,
          y = 772,
          width = 76,
          height = 38,
          rotation = 0,
          opacity = 1,
          gid = 616,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 264,
          y = 316,
          width = 76,
          height = 38,
          rotation = 0,
          opacity = 1,
          gid = 616,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 634,
          y = 323,
          width = 76,
          height = 38,
          rotation = 0,
          opacity = 1,
          gid = 616,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 340,
          width = 76,
          height = 38,
          rotation = 0,
          opacity = 1,
          gid = 2147484264,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 366.333,
          y = 787.333,
          width = 36,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 621,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 222,
          y = 326,
          width = 36,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 621,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "",
          type = "",
          shape = "rectangle",
          x = 566,
          y = 309,
          width = 36,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 621,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 262,
          y = 887,
          width = 36,
          height = 50,
          rotation = 0,
          opacity = 1,
          gid = 621,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 150.333,
          y = 280,
          width = 89.667,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "study.jack"
          }
        },
        {
          id = 176,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 356,
          y = 685.167,
          width = 262.803,
          height = 85.8333,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1"] = "* A bunch of dusty, dry history books.",
            ["text2"] = "* They seem to be standing in the way...",
            ["text3"] = "* ... Of something far more interesting."
          }
        },
        {
          id = 175,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 440,
          y = 240,
          width = 80,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1"] = "* Locked."
          }
        },
        {
          id = 184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 462.5,
          y = 803.917,
          width = 44,
          height = 26,
          rotation = 0,
          opacity = 1,
          gid = 620,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 100,
          y = 920,
          width = 40,
          height = 80,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "study.oldman",
            ["once"] = true
          }
        },
        {
          id = 219,
          name = "savepoint",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 840,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["text1"] = "* (The old man isn't here...)[wait:5]\n* (Susie looks like she's lost in thought in this place.)",
            ["text2"] = "* (But despite all that...)",
            ["text3"] = "* (You are filled with the power of investigating what happened here.)"
          }
        },
        {
          id = 220,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 150.333,
          y = 280,
          width = 169.667,
          height = 50,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "study.jack"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects_party2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 179,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 452.405,
          y = 795.61,
          width = 62,
          height = 60,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["cutscene"] = "study.book"
          }
        },
        {
          id = 196,
          name = "sprite",
          type = "",
          shape = "point",
          x = 478,
          y = 776,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["speed"] = 0.333333333,
            ["texture"] = "effects/shine_white"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 800,
          width = 80,
          height = 110,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "polygon",
          x = 190,
          y = 720,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polygon = {
            { x = -40, y = -40 },
            { x = 80, y = 80 },
            { x = 90, y = 80 },
            { x = -30, y = 80 },
            { x = -30, y = 200 },
            { x = -190, y = 200 },
            { x = -190, y = -720 },
            { x = 770, y = -720 },
            { x = 770, y = 480 },
            { x = -190, y = 480 },
            { x = -190, y = 280 },
            { x = -30, y = 280 },
            { x = -12, y = 321 },
            { x = 10, y = 348 },
            { x = 31, y = 365 },
            { x = 67, y = 382 },
            { x = 97, y = 390 },
            { x = 130, y = 396 },
            { x = 170, y = 400 },
            { x = 410, y = 400 },
            { x = 450, y = 396 },
            { x = 483, y = 390 },
            { x = 513, y = 382 },
            { x = 530, y = 374 },
            { x = 549, y = 364 },
            { x = 570, y = 348 },
            { x = 592, y = 321 },
            { x = 610, y = 280 },
            { x = 610, y = 80 },
            { x = 490, y = 80 },
            { x = 500, y = 80 },
            { x = 620, y = -40 },
            { x = 690, y = -40 },
            { x = 690, y = -440 },
            { x = 100, y = -440 },
            { x = 100, y = -520 },
            { x = -6, y = -520 },
            { x = -6, y = -440 },
            { x = -110, y = -440 },
            { x = -108, y = -40 }
          },
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 988,
          width = 240,
          height = 67,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 334,
          y = 1054,
          width = 42,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 1038,
          width = 32,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 624,
          y = 994,
          width = 28,
          height = 18,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 642,
          y = 1026,
          width = 28,
          height = 18,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 580,
          y = 680,
          width = 36,
          height = 40,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "polygon",
          x = 160,
          y = 623,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          polygon = {
            { x = 10, y = 17 },
            { x = 0, y = 17 },
            { x = 0, y = -263 },
            { x = 640, y = -263 },
            { x = 640, y = 17 },
            { x = 630, y = 17 },
            { x = 520, y = 127 },
            { x = 560, y = 87 },
            { x = 560, y = 81 },
            { x = 514, y = 69 },
            { x = 480, y = 63 },
            { x = 394, y = 57 },
            { x = 254, y = 57 },
            { x = 168, y = 63 },
            { x = 134, y = 69 },
            { x = 80, y = 81 },
            { x = 80, y = 87 },
            { x = 120, y = 127 }
          },
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 620,
          y = 690,
          width = 28,
          height = 26,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 404,
          y = 788,
          width = 160,
          height = 61,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 451,
          y = 760,
          width = 58,
          height = 28,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 282.25,
          y = 1018.5,
          width = 27,
          height = 18.25,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          type = "",
          shape = "rectangle",
          x = 142.333,
          y = 302,
          width = 42.3333,
          height = 23.6667,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          type = "",
          shape = "rectangle",
          x = 666,
          y = 289,
          width = 42,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          type = "",
          shape = "rectangle",
          x = 296,
          y = 282,
          width = 42,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          type = "",
          shape = "rectangle",
          x = 590,
          y = 738,
          width = 42,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          type = "",
          shape = "rectangle",
          x = 365,
          y = 700,
          width = 42,
          height = 20,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          type = "",
          shape = "rectangle",
          x = 246,
          y = 1011,
          width = 32,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 264,
          y = 296,
          width = 28,
          height = 18,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "",
          type = "",
          shape = "rectangle",
          x = 188,
          y = 320,
          width = 28,
          height = 18,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 277,
          width = 28,
          height = 18,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = 226,
          y = 292,
          width = 32,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 269,
          width = 32,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 213,
          name = "",
          type = "",
          shape = "rectangle",
          x = 570,
          y = 275,
          width = 32,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "",
          type = "",
          shape = "rectangle",
          x = 634,
          y = 303,
          width = 28,
          height = 18,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "",
          type = "",
          shape = "rectangle",
          x = 266,
          y = 853,
          width = 32,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "",
          type = "",
          shape = "rectangle",
          x = 370,
          y = 754,
          width = 32,
          height = 30,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 217,
          name = "",
          type = "",
          shape = "rectangle",
          x = 333,
          y = 714,
          width = 28,
          height = 18,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 218,
          name = "",
          type = "",
          shape = "rectangle",
          x = 558,
          y = 752,
          width = 28,
          height = 18,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 104,
          name = "entry_left",
          type = "",
          shape = "point",
          x = 40,
          y = 960,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "entry_door_1",
          type = "",
          shape = "point",
          x = 240,
          y = 300,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "spawn",
          type = "",
          shape = "point",
          x = 480,
          y = 910,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "objects_fog",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 145,
          name = "churchfog",
          type = "",
          shape = "point",
          x = -40,
          y = 80,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects_overlay",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 143,
          name = "texturescroller",
          type = "",
          shape = "point",
          x = -40,
          y = -120,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["type"] = "hsv"
          }
        },
        {
          id = 144,
          name = "filter",
          type = "",
          shape = "point",
          x = -120,
          y = 40.0006,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["type"] = "hsv2"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "controllers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 221,
          name = "toggle",
          type = "",
          shape = "point",
          x = 0,
          y = 0,
          width = 0,
          height = 0,
          rotation = 0,
          opacity = 1,
          visible = true,
          properties = {
            ["flag"] = "readCount",
            ["inverted"] = true,
            ["target"] = { id = 196 },
            ["value"] = 10
          }
        }
      }
    }
  }
}
